version: '3'
services:
  serviceRegistry:
    image: 'konghengsbilh/service_registry:0.0.1'
    container_name: Service-Registry
    ports:
      - '8761:8761'
  configServer:
    image: 'konghengsbilh/configserver:0.0.1'
    container_name: Config-Server
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceRegistry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceRegistry
  authenticationService:
    image: 'konghengsbilh/authentication_service:latest'
    container_name: Authentication-Service
    ports:
      - '9010:9010'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceRegistry:8761/eureka
      - CONFIG_SERVER_URL=configServer
    depends_on:
      configServer:
        condition: service_healthy
  cardSystemService:
    image: 'konghengsbilh/card_system_service:latest'
    container_name: Card-System-Service
    ports:
      - '9030:9030'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceRegistry:8761/eureka
      - CONFIG_SERVER_URL=configServer
    depends_on:
      configServer:
        condition: service_healthy
  coreBankingService:
    image: 'konghengsbilh/core_banking_service:latest'
    container_name: Core-Banking-Service
    ports:
      - '9020:9020'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceRegistry:8761/eureka
      - CONFIG_SERVER_URL=configServer
    depends_on:
      configServer:
        condition: service_healthy