version: '3'
services:
  serviceregistry:
    image: 'konghengsbilh/service_registry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'konghengsbilh/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
  authenticationservice:
    image: 'konghengsbilh/authentication_service:latest'
    container_name: authenticationservice
    ports:
      - '9010:9010'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy
  cardsystemservice:
    image: 'konghengsbilh/card_system_service:latest'
    container_name: cardsystemservice
    ports:
      - '9030:9030'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy
  corebankingservice:
    image: 'konghengsbilh/core_banking_service:latest'
    container_name: corebankingservice
    ports:
      - '9020:9020'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy